### ISSUE TITLE
Actual numbers report for Space and Namespace quotas

### ISSUE THREAD

**Issue by ragani** [paypal/NNAnalytics#229]
I see, we have Space and Namespace quotas utilization % for hdfs directories in NNA but it would be useful to have Actual numbers also for Space and Namespace quotas for the directories which have quotas implemented. Please let me know if you need additional information.

**Comment by pjeli** [comment]
For anyone else following here, it is always possible to hit the "[Explain]" button on the bottom quotas area of `suggestion.html` and select "List Directories by X Quota Assigned/Used". This will run a query (should be very quick, especially after #224 now), and get the numbers that @ragani is talking about.

This issue is reserved for storing these values in cache for faster look-up and not costing a query -- along with creating a data tables HTML page for easier viewing.
