### ISSUE TITLE
What does NNAnalytics do with journalnode?

### ISSUE THREAD

**Issue by Viking-Bird** [paypal/NNAnalytics#255]
I call the loadingStatus API and find the following output, why?
#
```
name: "LoadingEdits",
desc: "Loading edits",
status: "COMPLETE",
percentComplete: 1,
elapsedTime: 25300
```

**Comment by pjeli** [comment]
Hi @Viking-Bird,

This is meant to be the same as you see it on NameNode. It's just to show you how far along NNA is in the bootstrap process. Once it is running, the EditLogTailer takes over and reads / catches up the namespace via the QuorumJournalManagers / JournalNodes.

`/loadingStatus` is purely an administrative / informative view API for viewing how far long NNA is in the bootstrap process.

**Comment by Viking-Bird** [comment]
May I think so? NNA simply pulls the latest fsimage from the Active NameNode when calling the fetchNamespace API.This is not an initiative to update fsimage later.The information we get from journalnode just tells us what the latest fsimage offset is.

**Comment by pjeli** [comment]
Ah sorry @Viking-Bird - I'm afraid I don't quite understand what you are asking then. I will do my best to answer here but if I am heading in the wrong direction please correct me.

So firstly, you are correct that `/fetchNamespace` will just download the FsImage one time. You can then load that image and get NNA up and running.

The purpose of the JournalNodes (in the case of NNA) is to continue to keep NNA up-to-date. So that you don't need to run `fetchNamespace` over and over again.

Once NNA is up and running it will continue to fetch edit log batches from the JournalNodes and update  NNA in the background. You should be able to see this if you continue to refresh `/info` every minute or so. The output line `Current TxID: X` should eventually change and become `Current TxID: Y`, where Y > X.

**Comment by Viking-Bird** [comment]
OK,Thanks,I understand

**Comment by pjeli** [comment]
Thanks @Viking-Bird. :) I will go ahead and close this out now.

If you need more info just open another issue or message me on Gitter! Thanks!
